/* Auth Actions */
// Signup Actions
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Login Actions
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT = 'LOGOUT';

/* Product Actions */
export const GET_LATEST_PRODUCTS = 'GET_LATEST_PRODUCTS';
export const CLEAR_LATEST_PRODUCTS = 'CLEAR_LATEST_PRODUCTS';
export const LATEST_PRODUCTS_LOADING = 'LATEST_PRODUCTS_LOADING';
export const LATEST_PRODUCTS_ERROR = 'LATEST_PRODUCTS_ERROR';
export const GET_REFINED_PRODUCTS = 'GET_REFINED_PRODUCTS';
export const CLEAR_REFINED_PRODUCTS = 'CLEAR_REFINED_PRODUCTS';
export const REFINED_PRODUCTS_LOADING = 'REFINED_PRODUCTS_LOADING';
export const REFINED_PRODUCTS_ERROR = 'REFINED_PRODUCTS_ERROR';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const PRODUCT_DETAIL_LOADING = 'PRODUCT_DETAIL_LOADING';
export const CLEAR_PRODUCT_DETAIL = 'CLEAR_PRODUCT_DETAIL';
export const PRODUCT_DETAIL_ERROR = 'PRODUCT_DETAIL_ERROR';

// Uploaded products actions
export const GET_UPLOADED_PRODUCTS_START = 'GET_UPLOADED_PRODUCTS_START';
export const GET_UPLOADED_PRODUCTS_SUCCESS = 'GET_UPLOADED_PRODUCTS_SUCCESS';
export const GET_UPLOADED_PRODUCTS_FAILURE = 'GET_UPLOADED_PRODUCTS_FAILURE';

// providers section actions
export const FETCH_PROVIDERS = 'FETCH_PROVIDERS';
export const FETCHING_PROVIDERS = 'FETCHING_PROVIDERS';
export const FETCH_PROVIDERS_ERROR = 'FETCH_PROVIDERS_ERROR';

// cart actions
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ADDING_ITEM = 'ADDING_ITEM';
export const REMOVING_ITEM = 'REMOVING_ITEM';
export const CART_ERROR = 'CART_ERROR';
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const FETCHING_CART_ITEMS = 'FETCHING_CART_ITEMS';
export const REMOVE_ALL = 'REMOVE_ALL';
/* Global Action Types */
export const START_LOADING_APP = 'START_LOADING_APP';
export const FINISH_LOADING_APP = 'FINISH_LOADING_APP';
export const SET_GLOBAL_ERROR = 'SET_GLOBAL_ERROR';
export const CLEAR_GLOBAL_ERROR = 'CLEAR_GLOBAL_ERROR';
